// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGJ4Dm7eszrDHdbiQlj6mqYn5vfLpk_WA',
    appId: '1:987014562468:web:6764f8d2ad435144699c31',
    messagingSenderId: '987014562468',
    projectId: 'vocap-dev',
    authDomain: 'vocap-dev.firebaseapp.com',
    databaseURL: 'https://vocap-dev-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vocap-dev.firebasestorage.app',
    measurementId: 'G-RTE8SJ589F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxz8bNW2aKI6YTMNPVS7-WeiVIXUUgyoA',
    appId: '1:987014562468:android:1565440af05ac3de699c31',
    messagingSenderId: '987014562468',
    projectId: 'vocap-dev',
    databaseURL: 'https://vocap-dev-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vocap-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiVpfHvIeErue3P672_mZMXS256dSS8Wg',
    appId: '1:987014562468:ios:32b9f0719eb4cbc1699c31',
    messagingSenderId: '987014562468',
    projectId: 'vocap-dev',
    databaseURL: 'https://vocap-dev-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vocap-dev.firebasestorage.app',
    iosClientId: '987014562468-vq39rml147pn5p9uhm7u28g6l9lj4pur.apps.googleusercontent.com',
    iosBundleId: 'com.stone.vocap.dev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiVpfHvIeErue3P672_mZMXS256dSS8Wg',
    appId: '1:987014562468:ios:b3a83cc33ff0e9ca699c31',
    messagingSenderId: '987014562468',
    projectId: 'vocap-dev',
    databaseURL: 'https://vocap-dev-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vocap-dev.firebasestorage.app',
    iosClientId: '987014562468-20o5i09p81oh2bfhe1ah8csmlt5qstt6.apps.googleusercontent.com',
    iosBundleId: 'com.stone.vocap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGJ4Dm7eszrDHdbiQlj6mqYn5vfLpk_WA',
    appId: '1:987014562468:web:12c5dc1384d5e07f699c31',
    messagingSenderId: '987014562468',
    projectId: 'vocap-dev',
    authDomain: 'vocap-dev.firebaseapp.com',
    databaseURL: 'https://vocap-dev-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vocap-dev.firebasestorage.app',
    measurementId: 'G-4V8Z77JK9D',
  );

}