name: vocap
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  equatable: ^2.0.5
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.6.1
  touchable_opacity: ^1.2.0
  cached_network_image: ^3.4.1
  lottie: ^3.1.3
  go_router: ^14.3.0
  riverpod_builder: ^0.2.1
  firebase_core: ^3.7.0
  firebase_analytics: ^11.3.4
  firebase_crashlytics: ^4.1.4
  firebase_auth: ^5.3.2
  firebase_messaging: ^15.1.4
  firebase_storage: ^12.3.5
  firebase_performance: ^0.10.0+9
  firebase_in_app_messaging: ^0.8.0+9
  google_sign_in: ^6.2.2
  fpdart: ^1.1.1
  dio: ^5.7.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner:
  riverpod_lint: ^2.6.2
  go_router_builder: ^2.7.1
  riverpod_generator:
  custom_lint:
  flutter_flavorizr: ^2.2.3
  flutter_launcher_icons: ^0.14.1


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lottie/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700